export const SANDBOX_LIMITS = {
  FREE_RUNS_PER_DAY: 5,
  PRO_RUNS_PER_DAY: 50,
  FREE_TIMEOUT_MS: 30_000,
  PRO_TIMEOUT_MS: 120_000,
  MAX_INPUT_CHARS: 10_000,
  MAX_OUTPUT_CHARS: 50_000,
  MAX_TEST_CASES_PER_SKILL: 10,
  CACHE_TTL_SECONDS: 3600,
} as const;

export const AGENT_LIMITS = {
  FREE_MAX_AGENTS: 3,
  PRO_MAX_AGENTS: 20,
  FREE_EXECUTIONS_PER_MONTH: 100,
  PRO_EXECUTIONS_PER_MONTH: 5_000,
} as const;
