export const QUALITY_SCORE = {
  MIN: 0,
  MAX: 100,

  SCHEMA_MAX: 25,
  SCHEMA_FIELDS_PRESENT: 10,
  SCHEMA_DESCRIPTION_LENGTH: 5,
  SCHEMA_SEMVER: 5,
  SCHEMA_VALID_CATEGORY: 5,

  INSTRUCTION_MAX: 75,
  INSTRUCTION_MIN_LENGTH: 10,
  INSTRUCTION_LONG_BONUS: 5,
  INSTRUCTION_STRUCTURED_PHASES: 15,
  INSTRUCTION_IO_SPEC: 10,
  INSTRUCTION_ERROR_HANDLING: 10,
  INSTRUCTION_GUARDRAILS: 10,
  INSTRUCTION_EXAMPLES: 10,
  INSTRUCTION_OUTPUT_FORMAT: 5,

  THRESHOLDS: {
    MIN_DESCRIPTION_CHARS: 50,
    MIN_INSTRUCTION_CHARS: 500,
    LONG_INSTRUCTION_CHARS: 2000,
    MIN_PUBLISH_SCORE: 20,
  },
} as const;

export const RATING = {
  MIN: 1,
  MAX: 5,
} as const;
